-- Crear todos los schemas
CREATE SCHEMA IF NOT EXISTS iam;
;
CREATE SCHEMA IF NOT EXISTS core;
;
CREATE SCHEMA IF NOT EXISTS consumo;
;
CREATE SCHEMA IF NOT EXISTS energiaops;
;
CREATE SCHEMA IF NOT EXISTS educacion;
;
CREATE SCHEMA IF NOT EXISTS mantenimiento;
;
CREATE SCHEMA IF NOT EXISTS audit;
;
CREATE SCHEMA IF NOT EXISTS analitica;
;
